version: "3.9"

services:
  pr-reviewer-service:
    build:
      context: .
      dockerfile: Dockerfile

    pull_policy: build

    container_name: pr-reviewer-service-container
    hostname: pr-reviewer-service

    ports:
      - "8080:8080"
    environment:
      CONFIG_PATH: "/app/configs/pr-reviewer-service.json"
    restart: unless-stopped
        
